
//get message from user id 1
GET http://localhost:5097/api/v1/Message HTTP/1.1


###

//Post new message to user id 1
POST http://localhost:5097/api/v1/Message?SendToUid=1 HTTP/1.1
content-type: application/json

{
    "Content" : "my name is jordy"
}

###

//Post new message to user id 4
POST http://localhost:5097/api/v1/Message?SendToUid=4 HTTP/1.1
content-type: application/json

{
    "Content" : "my name is max"
}


###

//Update message read status for current user
PUT http://localhost:5097/api/v1/Message?messageId=4  HTTP/1.1

###
