
// Change user settings
// redirects to login screen if email or password is changed, to re-login
PUT http://localhost:5097/api/v1/Profile HTTP/1.1
content-type: application/json

{
    "FirstName": "Oliver",
    "LastName": "Breth",
    "Email": "oliver@example.com",
    "Password": "supersecret",
    "RecurringDays": "tu"
}

// Revert changes
###
PUT http://localhost:5097/api/v1/Profile HTTP/1.1
content-type: application/json

{
    "FirstName": "Max",
    "LastName": "Bretherton",
    "Email": "max@example.com",
    "Password": "secret",
    "RecurringDays": "mo,tu,we"
}
###
POST http://localhost:5097/api/v1/login/login HTTP/1.1
content-type: application/json

{
    "Username": "oliver@example.com",
    "Password": "supersecret"
}
###


// Get profile page
GET http://localhost:5097/api/v1/Profile/maxbretherton HTTP/1.1
####


// arrive to the office
PUT http://localhost:5097/api/v1/Profile/attendance/arrive HTTP/1.1
####


// leave the office
PUT http://localhost:5097/api/v1/Profile/attendance/leave HTTP/1.1
###